### PR TITLE
Fix ENS and UNS names not visible in UI

### LINKED ISSUE #823: ENS names are lagging to become visible
1. Clear localstorage
2. Add account with an ens/uns name
3. Wait a minute 
4. Check localstorage to mkae sure the name was cached

Result: name is not replacing the address in the UI even if it is available in the cache
Expected: name should be visible in the UI as soon as it is loaded

### PR DESCRIPTION
**Pull request by xpaczka**
## Issues connected

Resolves #823 

## What has been done

- Fixed ENS and UNS names not updated automatically (without reload)
- Added `useCachedWalletName` hook

## Testing

- [x] Clear `localStorage`
- [x] Connect wallet
- [x] After a short interval, account name is automatically updated
- [x] Reload the page, the name is still visible

### CODE REVIEW

File: src/shared/hooks/wallets.ts [hunk 1]
```diff
@@ -270,3 +275,29 @@ export function useWalletChange() {
...
+      if (!walletAddress) return
+
+      const cachedNames = localStorage.getItem(LOCAL_STORAGE_CACHED_NAMES)
+      if (!cachedNames) return
+
+      const parsedCachedNames: CachedNames = JSON.parse(cachedNames)
+      const { ens, uns } = parsedCachedNames[walletAddress]
+
+      if (ens) setAccountName(ens.name)
+      if (uns) setAccountName(uns.name)
```
Comment (jagodarybacka) [inline src/shared/hooks/wallets.ts:294]: ENS names should override UNS names if user has both (same as we have it in the wallet)

File: src/shared/hooks/wallets.ts [hunk 2]
```diff
@@ -270,3 +275,29 @@ export function useWalletChange() {
...
+    }
+
+    window.addEventListener("storage", handleCachedNamesUpdate)
+
+    return () => window.removeEventListener("storage", handleCachedNamesUpdate)
```
Comment (jagodarybacka) [inline src/shared/hooks/wallets.ts:299]: Feels like we are doing something weird trying to communicate between a util and a hook via events on the window. I feel like we are trying to achieve the same thing here as we would have if we just triggered the change on the redux slice?

File: src/ui/Nav/AccountInfo.tsx [hunk 3]
```diff
@@ -10,7 +10,11 @@ import { getRealmColor } from "shared/constants"
 import Avatar from "shared/components/Media/Avatar"
 import AccountDropdown from "./AccountDropdown"
 
-export default function AccountInfo() {
+type AccountInfoProps = {
+  accountName: string | null
```
Comment (jagodarybacka) [inline src/ui/Nav/AccountInfo.tsx:14]: why can't we just rely on the `const name = useDappSelector(selectWalletName)`? having two sources of truth here smells like a bad idea.

**Review by jagodarybacka — COMMENTED** [review]
I feel like we were missing some connections between utils <> cache <> redux but to me it seems like they are still not quite there yet. What about utilizing some redux features (async thunks? maybe names need to have their own service?) to trigger the state changes correctly without a need to use events on window object?

**Review by jagodarybacka — APPROVED** [review]
I don't love this approach but let's just make it work 🚀
