### PR TITLE
Fix assistant messaging

### LINKED ISSUE #866: `Why join a Realm` assistant message not displayed?
I can't make the dApp to display the `Why join a Realm` assistant message. Tried on a completely new account that got some TAHO sent to it. I was able to see the `Welcome to Subscape, Nomad` message after entering island. But entering/exiting realms didn't result in showing the `Why join a Realm` message.
I'm not sure if I'm doing something wrong or if there's a bug here...

### PR DESCRIPTION
**Pull request by xpaczka**
Resolves #866 

## What has been done
Messages from assistant were not displayed correctly due to unnecessary `useEffect`. Also extracted some `Island` logic to `useOnRealmClick` hook.

## Testing
- [x] Clear `localStorage`
- [x] Connect wallet that is not staked in any realm
- [x] After entering portal, `Welcome to Subscape, Nomad` message appears
- [x] After clicking on realm for first time, `Why join a realm` message appears

### CODE REVIEW

**Review by michalinacienciala — DISMISSED** [review]
I've tested the PR, assistant behaves as expected. One troubling thing I noticed during testing on the preview was that several times when I changed the account connected to dApp or disconnected an account, the spinning wheel shown during connecting/disconnecting was stuck in a loop (not progressing to the next view). We've seen this behavior before, but this time it was happening for me quite often. But given the scope of the change in this PR, I think it likely wasn't related to the change and was just a coincidence.
Anyway, I'm accepting the PR from the point of view of testing (didn't review the code, so I'm not merging). And I'll keep an eye on the spinning wheel's performance on other environments.

File: src/shared/hooks/realm.ts [hunk 1]
```diff
@@ -94,3 +99,29 @@ export function usePanelRealmClose() {
...
+
+export function useOnRealmClick() {
+  const realmId = useDappSelector(selectDisplayedRealmId)
+  const dispatch = useDappDispatch()
+  const { updateAssistant, assistantVisible } = useAssistant()
+
+  const { value: visitedRealm, updateStorage: updateVisitedRealm } =
+    useLocalStorageChange<boolean>(LOCAL_STORAGE_VISITED_REALM)
+
+  const onRealmClick = (id: string) => {
```
Comment (jagodarybacka) [inline src/shared/hooks/realm.ts:111]: Can we wrap it in the `useCallback` so we are returning stable referance?

**Review by jagodarybacka — CHANGES_REQUESTED** [review]

**Review by jagodarybacka — APPROVED** [review]
